// ARQUIVO: config.ts
// OBJETIVO: Centralizar todas as configurações e constantes do sistema.

// =================================================================
// 1. URL DO BACKEND (GOOGLE APPS SCRIPT)
// URL final do seu novo projeto de Apps Script.
// =================================================================
export const BACKEND_URL = 'https://script.google.com/macros/s/AKfycbxN_FibhCjJOE5sEUDkJ9TruwP08Rr9otYLYZ6izVYE0RrYy-C7PuGNEg2NUCo-Xp9o6A/exec';


// =================================================================
// 2. IDs DOS TEMPLATES DE DOCUMENTOS (GOOGLE DOCS)
// IDs da sua nova pasta de templates.
// =================================================================
export const TEMPLATE_IDS = {
  // Contratos
  CONTRATO_TITULAR: '1oL-rTrqrpBRcBpYOdP3tfi8Qy6HHQDvLitjbMnBWKbg',
  CONTRATO_REP_INCAPAZ: '11I0Gv0ENLoQYnLCn_sPkdtZWTXVOMRK84rYWAnGdKwI',

  // Procurações
  PROCURACAO_TITULAR: '1KDbreHs2qKiSmxm0_alb-u-89znvL1vtw3qlSxg32s8',
  PROCURACAO_REP_INCAPAZ: '1-Pep1Hplp6QXteqOAqI6HpVYwHVo1ZZ15rgjfvUyu6s',
  
  // Declarações
  DECLARACAO_RESIDENCIA_TITULAR: '10QlSdNjRvaimK9pgbun_MA65tDV2rajsZcjZwQyGTTM',
  DECLARACAO_RESIDENCIA_REP_INCAPAZ: '1A0UIUc3ApnRNkBqpmn8UJfM4pKMa8YG8GaVKt0p_Tko',
  
  // Anexos e Casos Específicos
  ANEXO_PROCURACAO_REP_ANALFABETO: '1fJDahgYfPGopY43JyfQVac5BL8YVlnUj29i4tx56eSA',
  ANEXO_PROCURACAO_ANALFABETO: '1lZtndaEwKofiQq78xTLFP4wIz-p-Mlhv_Od_pIaEzro',
  ANEXO_PROCURACAO_ROGO: '1Uaz-3ThzoBiQoXHqyQMw5MgknmvRPEZ1u3a0ddYD6rI',
  ANEXO_DECLARACAO_SEPARACAO_FATO: '1F5nU9SP6aFlcVsp-rdwAXFLOVQuEAjE1-5shN5Q7ZO8',
  ANEXO_DECLARACAO_RESIDENCIA_SEM_COMPROVANTE: '1fRfejrQJPBaHcpX9oXq4hRa2DVius_LGtYJ78fLcpTY',
};


// =================================================================
// 3. CONFIGURAÇÃO DOS DOCUMENTOS GERÁVEIS
// Mapeia os documentos que aparecerão na interface para seleção.
// =================================================================
export const DOCUMENTOS_CONFIG = [
  { id: 'CONTRATO_TITULAR', label: 'CONTRATO DE HONORARIOS TITULAR ASSINA', templateId: TEMPLATE_IDS.CONTRATO_TITULAR },
  { id: 'PROCURACAO_TITULAR', label: 'PROCURACAO TITULAR ASSINA', templateId: TEMPLATE_IDS.PROCURACAO_TITULAR },
  { id: 'DECLARACAO_RESIDENCIA_TITULAR', label: 'DECLARACAO DE RESIDENCIA TITULAR ASSINA', templateId: TEMPLATE_IDS.DECLARACAO_RESIDENCIA_TITULAR },
  { id: 'CONTRATO_REP_INCAPAZ', label: 'CONTRATO DE HONORARIOS REPRESENTANTE ASSINA MENOR/INCAPAZ', templateId: TEMPLATE_IDS.CONTRATO_REP_INCAPAZ },
  { id: 'PROCURACAO_REP_INCAPAZ', label: 'PROCURACAO REPRESENTANTE ASSINA MENOR/INCAPAZ', templateId: TEMPLATE_IDS.PROCURACAO_REP_INCAPAZ },
  { id: 'DECLARACAO_RESIDENCIA_REP_INCAPAZ', label: 'DECLARACAO RESIDENCIA - REPRESENTANTE ASSINA MENOR/INCAPAZ', templateId: TEMPLATE_IDS.DECLARACAO_RESIDENCIA_REP_INCAPAZ },
  { id: 'ANEXO_PROCURACAO_REP_ANALFABETO', label: 'ANEXO PROCURACAO REPRESENTANTE ANALFABETO MENOR/INCAPAZ COM TESTEMUNHAS', templateId: TEMPLATE_IDS.ANEXO_PROCURACAO_REP_ANALFABETO },
  { id: 'ANEXO_PROCURACAO_ANALFABETO', label: 'ANEXO PROCURACAO ANALFABETO COM TESTEMUNHAS', templateId: TEMPLATE_IDS.ANEXO_PROCURACAO_ANALFABETO },
  { id: 'ANEXO_PROCURACAO_ROGO', label: 'ANEXO PROCURACAO A ROGO - ANALFABETO COM ROGADO E TESTEMUNHAS', templateId: TEMPLATE_IDS.ANEXO_PROCURACAO_ROGO },
  { id: 'ANEXO_DECLARACAO_SEPARACAO_FATO', label: 'ANEXO DECLARACAO SEPARACAO DE FATO', templateId: TEMPLATE_IDS.ANEXO_DECLARACAO_SEPARACAO_FATO },
  { id: 'ANEXO_DECLARACAO_RESIDENCIA_SEM_COMPROVANTE', label: 'ANEXO DECLARACAO RESIDENCIA - SEM COMPROVANTE DE RESIDENCIA', templateId: TEMPLATE_IDS.ANEXO_DECLARACAO_RESIDENCIA_SEM_COMPROVANTE },
];
